#!/bin/bash

set -e -u

WORKDIR=${HOME}/autobuild

function usage() {
	echo "Usage: $0 1.2|1.3 minimal|full"
}

if (( $# != 2 )) ; then
	usage
	exit 1
fi

case "$1" in
	1.3)
		BUILDVER=1.3 ;;
	1.2)
		BUILDVER=1.2 ;;
	*)
		usage
		exit 1
	;;
esac

case "$2" in
	full)
		CONFIG_EXTRAFLAGS=""
		EXTRAVERSION=""
		;;
	minimal)
		CONFIG_EXTRAFLAGS=" --disable-cups --disable-lcms --disable-xml --without-python "
		EXTRAVERSION="minimal"
		;;
	*)
		usage
		exit 1
	;;
esac

DATEI=`date -I`
BUILDDIR="${WORKDIR}/build/${DATEI}/${BUILDVER}-${EXTRAVERSION}"
INSTALLDIR="${WORKDIR}/install/${DATEI}/${BUILDVER}-${EXTRAVERSION}"
BUILDLOG="${INSTALLDIR}/${BUILDVER}-${EXTRAVERSION}.log"

mkdir -p "${BUILDDIR}" "${INSTALLDIR}" 2>/dev/null || true

case "${BUILDVER}" in
	1.3)
		tag=" -r Version13x "
		;;
	1.2)
		tag=""
		;;
	*)
		echo "Error: invalid version"
		exit 2
		;;
esac

cd "${WORKDIR}/build/${DATEI}"

export CVSROOT=":ext:wwwpost:/cvs"
export CVS_RSH="ssh"
cvs co ${tag} -d "${BUILDVER}-${EXTRAVERSION}" "Scribus" >>"${BUILDLOG}" 2>&1 

cd "${BUILDDIR}"

echo "Generating configure and Makefiles" >>"${BUILDLOG}"
if ! make -f Makefile.cvs >>"${BUILDLOG}" 2>&1 ; then
	echo "The build appears to have failed when generating makefiles." >&2
	echo "See ${BUILDLOG} for the build output." >&2
	exit 3
fi

echo "Configuring with \"${CONFIG_EXTRAFLAGS}\"" >>"${BUILDLOG}"
if ! ./configure --enable-debug --prefix="${INSTALLDIR}" $CONFIG_EXTRAFLAGS >>"${BUILDLOG}" 2>&1; then
	echo "The build appears to have failed when configuring." >&2
	echo "See ${BUILDLOG} for the build output." >&2
	exit 3
fi

echo "Building..." >>"${BUILDLOG}"
if ! make >>"${BUILDLOG}" 2>&1; then
	echo "The build appears to have failed while compiling." >&2
	echo "See ${BUILDLOG} for the build output." >&2
	exit 3
fi

echo "Installing..." >>"${BUILDLOG}"
if ! make install >>"${BUILDLOG}" 2>&1; then
	echo "The build appears to have failed while installing." >&2
	echo "See ${BUILDLOG} for the build output." >&2
	exit 3
fi

echo
echo "All appears to have built OK"
