######################################################################
# Automatically generated by qmake (1.07a) Mon Mar 21 17:23:58 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += colorwheelwidget.h cwdialog.h
SOURCES += colorwheelwidget.cpp cwdialog.cpp main.cpp
